### PR TITLE
Dep/remove/brfs

### PR DESCRIPTION
**Pull request by thisconnect**
just to test #2

### CODE REVIEW

**Comment by thisconnect** [comment]
1st 
https://travis-ci.org/ipld/js-ipld-dag-pb/builds/291222774 is OK
uses browser tests https://github.com/ipld/js-ipld-dag-pb/blob/master/package.json#L11

2nd
https://travis-ci.org/libp2p/js-libp2p-crypto/builds/291226394  1/2 FAIL (2 failing in Node v6)
https://travis-ci.org/libp2p/js-libp2p-crypto/jobs/291226396#L2239
going back proton@1.0.0  tests still fail, but also for Node v8 
https://travis-ci.org/libp2p/js-libp2p-crypto/jobs/291228713#L3373 
indicating that tests for js-listp2p-crypto randomlyish fail.? 
Build history suggest that all should pass https://travis-ci.org/libp2p/js-libp2p-crypto/builds

3rd 
https://travis-ci.org/ipfs/js-ipfs-bitswap/builds/291232204 looks ok but is hanging somewhere

**Comment by dignifiedquire** [comment]
Thanks for checking
- pretty sure the crypto failure is due to CI being slow from the logs, not an actual problem
- restarted bitswap, not sure what the issue was there

**Comment by thisconnect** [comment]
bitswap also has 2 pending with protons@1.0.0 as well
https://github.com/ipfs/js-ipfs-bitswap/pull/153

**Comment by dignifiedquire** [comment]
Shipping it, ci is just sad sometimes I believe

**Pull request merged**
